---
package_source: "local"
ubuntu_18_apt_repo: "deb [trusted=yes] file:///xroad /"

rhel_repo_baseurl: "file:///xroad"
rhel_repo_gpgcheck: "no"
rhel_repo_gpgkey: ""
rhel_repo_repogpgcheck: "no"
rhel_repo_metadataexpire: 60

