---
package_source: "remote"

xroad_repo_baseurl: "https://artifactory.niis.org"
xroad_repo_key:  "https://artifactory.niis.org/api/gpg/key/public"

ubuntu_18_apt_key:  "{{xroad_repo_key}}"
ubuntu_18_repo_url: "{{xroad_repo_baseurl}}/xroad-release-deb"
ubuntu_18_apt_repo: "deb {{ubuntu_18_repo_url}} bionic-current main"

rhel_repo_baseurl: "{{xroad_repo_baseurl}}/xroad-release-rpm/rhel/{{ansible_distribution_major_version}}/current"
rhel_repo_gpgcheck: "yes"
rhel_repo_gpgkey: "{{xroad_repo_key}}"
rhel_repo_repogpgcheck: "yes"
rhel_repo_metadataexpire: "21600"
